---
- hosts: nodes 
  vars_files:
    - var.yml
  become: true
  tasks:
    #==========================================================================
    - name: Install apache2
      apt: name=apache2 update_cache=no state=latest
      with_items:
        - apache2 

    - name: Enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
         - restart apache2
  
    #==========================================================================
    - name: Install MySQL
      action: apt pkg={{ item }} state=present
      with_items:
      - build-essential
      - libmysqlclient-dev
      - python3-dev
      - python3-mysqldb
      - python3-mysql.connector
      - mysql-server
      - mysql-client
  
    - name: Copying .my.cnf to remote
      become: true
      copy:
        src: .my.cnf
        dest: /root/.my.cnf
        owner: root
        group: root
  
    - name: Start the MySQL service
      action: service name=mysql state=started
  
    - name: Remove the test database
      mysql_db: name=test state=absent
  
    - name: Create deploy user for mysql
      mysql_user: user="deploy" host="%" password={{mysql_db_password}} priv=*.*:ALL,GRANT
  
    - name: Ensure anonymous users are not in the database
      mysql_user: user="" host={{ item }} state=absent
      with_items:
      - 127.0.0.1
      - ::1
      - localhost
  
    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{ item }} password={{mysql_db_password}}
      with_items:
      - 127.0.0.1
      - ::1
      - localhost
 
    #==========================================================================
    - name: Install PHP
      apt: name={{item}} update_cache=no state=present
      with_items:
        - php 
        - libapache2-mod-php 
        - php-fpm
   
    - name: Copying info.php to remote
      become: true
      copy:
        src: info.php 
        dest: /var/www/html/info.php 
        owner: root
        group: root

    #==========================================================================
    - name: Install WordPress
      apt: name={{item}} update_cache=no state=present
      with_items:
        - wordpress
        - php
        - libapache2-mod-php
        - mysql-server
        - php-mysql
    
    - name: Copying wordpress.conf to remote /etc/apache2/sites-available/
      become: true
      copy:
        src: wordpress.conf 
        dest: /etc/apache2/sites-available/wordpress.conf
        owner: root
        group: root

    - name: Enable the site
      become: true
      shell: a2ensite wordpress 

    - name: Enable URL rewriting
      become: true
      shell: a2enmod rewrite 

    - name: Reload Apache2 
      become: true
      shell: service apache2 reload  

    - name: Copying config-localhost.php to remote /etc/wordpress/
      become: true
      copy:
        src: config-localhost.php 
        dest: /etc/wordpress/config-localhost.php 
        owner: root
        group: root

    - name: Enable MySQL 
      become: true
      shell: service mysql start 

  handlers:
    - name: Restart apache2
      service: name=apache2 state=restarted

    - name: Restart php7.4-fpm
      service: name=php7.4-fpm state=restarted

    - name: Restart nginx
      service: name=nginx state=restarted

